namespace OplusEdlTool
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabFirehose = new System.Windows.Forms.TabPage();
            this.btnRunFirehose = new System.Windows.Forms.Button();
            this.btnBrowseSig = new System.Windows.Forms.Button();
            this.btnBrowseDigest = new System.Windows.Forms.Button();
            this.btnBrowseDevPrg = new System.Windows.Forms.Button();
            this.txtSig = new System.Windows.Forms.TextBox();
            this.txtDigest = new System.Windows.Forms.TextBox();
            this.txtDevPrg = new System.Windows.Forms.TextBox();
            this.lblSig = new System.Windows.Forms.Label();
            this.lblDigest = new System.Windows.Forms.Label();
            this.lblDevPrg = new System.Windows.Forms.Label();
            this.tabRead = new System.Windows.Forms.TabPage();
            this.btnRunRead = new System.Windows.Forms.Button();
            this.btnAddXmlRead = new System.Windows.Forms.Button();
            this.lstXmlRead = new System.Windows.Forms.ListBox();
            this.tabWrite = new System.Windows.Forms.TabPage();
            this.btnRunWrite = new System.Windows.Forms.Button();
            this.btnAddXmlWrite = new System.Windows.Forms.Button();
            this.lstXmlWrite = new System.Windows.Forms.ListBox();
            this.tabCleanup = new System.Windows.Forms.TabPage();
            this.btnCleanup = new System.Windows.Forms.Button();
            this.txtLog = new System.Windows.Forms.TextBox();
            this.tabPartitions = new System.Windows.Forms.TabPage();
            this.btnReadPartitions = new System.Windows.Forms.Button();
            this.lvPartitions = new System.Windows.Forms.ListView();
            this.colName = new System.Windows.Forms.ColumnHeader();
            this.colStart = new System.Windows.Forms.ColumnHeader();
            this.colEnd = new System.Windows.Forms.ColumnHeader();
            this.colSize = new System.Windows.Forms.ColumnHeader();
            this.colType = new System.Windows.Forms.ColumnHeader();
            this.colLun = new System.Windows.Forms.ColumnHeader();
            this.splitPartitions = new System.Windows.Forms.SplitContainer();
            this.btnBackupSelected = new System.Windows.Forms.Button();
            this.btnWriteSelected = new System.Windows.Forms.Button();
            this.tabControl.SuspendLayout();
            this.tabFirehose.SuspendLayout();
            this.tabRead.SuspendLayout();
            this.tabWrite.SuspendLayout();
            this.tabCleanup.SuspendLayout();
            this.tabPartitions.SuspendLayout();
            this.SuspendLayout();
            this.tabControl.Controls.Add(this.tabFirehose);
            this.tabControl.Controls.Add(this.tabRead);
            this.tabControl.Controls.Add(this.tabWrite);
            this.tabControl.Controls.Add(this.tabCleanup);
            this.tabControl.Controls.Add(this.tabPartitions);
            this.tabControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl.Location = new System.Drawing.Point(0, 0);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new System.Drawing.Size(784, 281);
            this.tabFirehose.Controls.Add(this.btnRunFirehose);
            this.tabFirehose.Controls.Add(this.btnBrowseSig);
            this.tabFirehose.Controls.Add(this.btnBrowseDigest);
            this.tabFirehose.Controls.Add(this.btnBrowseDevPrg);
            this.tabFirehose.Controls.Add(this.txtSig);
            this.tabFirehose.Controls.Add(this.txtDigest);
            this.tabFirehose.Controls.Add(this.txtDevPrg);
            this.tabFirehose.Controls.Add(this.lblSig);
            this.tabFirehose.Controls.Add(this.lblDigest);
            this.tabFirehose.Controls.Add(this.lblDevPrg);
            this.tabFirehose.Location = new System.Drawing.Point(4, 29);
            this.tabFirehose.Name = "tabFirehose";
            this.tabFirehose.Padding = new System.Windows.Forms.Padding(3);
            this.tabFirehose.Size = new System.Drawing.Size(776, 248);
            this.tabFirehose.Text = "Enter Firehose";
            this.tabFirehose.UseVisualStyleBackColor = true;
            this.btnRunFirehose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRunFirehose.Location = new System.Drawing.Point(646, 196);
            this.btnRunFirehose.Name = "btnRunFirehose";
            this.btnRunFirehose.Size = new System.Drawing.Size(112, 34);
            this.btnRunFirehose.Text = "Run";
            this.btnRunFirehose.UseVisualStyleBackColor = true;
            this.btnRunFirehose.Click += new System.EventHandler(this.btnRunFirehose_Click);
            this.btnBrowseSig.Location = new System.Drawing.Point(704, 130);
            this.btnBrowseSig.Name = "btnBrowseSig";
            this.btnBrowseSig.Size = new System.Drawing.Size(54, 34);
            this.btnBrowseSig.Text = "...";
            this.btnBrowseSig.UseVisualStyleBackColor = true;
            this.btnBrowseSig.Click += new System.EventHandler(this.btnBrowseSig_Click);
            this.btnBrowseDigest.Location = new System.Drawing.Point(704, 80);
            this.btnBrowseDigest.Name = "btnBrowseDigest";
            this.btnBrowseDigest.Size = new System.Drawing.Size(54, 34);
            this.btnBrowseDigest.Text = "...";
            this.btnBrowseDigest.UseVisualStyleBackColor = true;
            this.btnBrowseDigest.Click += new System.EventHandler(this.btnBrowseDigest_Click);
            this.btnBrowseDevPrg.Location = new System.Drawing.Point(704, 30);
            this.btnBrowseDevPrg.Name = "btnBrowseDevPrg";
            this.btnBrowseDevPrg.Size = new System.Drawing.Size(54, 34);
            this.btnBrowseDevPrg.Text = "...";
            this.btnBrowseDevPrg.UseVisualStyleBackColor = true;
            this.btnBrowseDevPrg.Click += new System.EventHandler(this.btnBrowseDevPrg_Click);
            this.txtSig.Location = new System.Drawing.Point(144, 132);
            this.txtSig.Name = "txtSig";
            this.txtSig.Size = new System.Drawing.Size(554, 31);
            this.txtDigest.Location = new System.Drawing.Point(144, 82);
            this.txtDigest.Name = "txtDigest";
            this.txtDigest.Size = new System.Drawing.Size(554, 31);
            this.txtDevPrg.Location = new System.Drawing.Point(144, 32);
            this.txtDevPrg.Name = "txtDevPrg";
            this.txtDevPrg.Size = new System.Drawing.Size(554, 31);
            this.lblSig.AutoSize = true;
            this.lblSig.Location = new System.Drawing.Point(22, 135);
            this.lblSig.Name = "lblSig";
            this.lblSig.Size = new System.Drawing.Size(34, 21);
            this.lblSig.Text = "sig";
            this.lblDigest.AutoSize = true;
            this.lblDigest.Location = new System.Drawing.Point(22, 85);
            this.lblDigest.Name = "lblDigest";
            this.lblDigest.Size = new System.Drawing.Size(57, 21);
            this.lblDigest.Text = "digest";
            this.lblDevPrg.AutoSize = true;
            this.lblDevPrg.Location = new System.Drawing.Point(22, 35);
            this.lblDevPrg.Name = "lblDevPrg";
            this.lblDevPrg.Size = new System.Drawing.Size(72, 21);
            this.lblDevPrg.Text = "devprg";
            this.tabRead.Controls.Add(this.btnRunRead);
            this.tabRead.Controls.Add(this.btnAddXmlRead);
            this.tabRead.Controls.Add(this.lstXmlRead);
            this.tabRead.Location = new System.Drawing.Point(4, 29);
            this.tabRead.Name = "tabRead";
            this.tabRead.Padding = new System.Windows.Forms.Padding(3);
            this.tabRead.Size = new System.Drawing.Size(776, 248);
            this.tabRead.Text = "Read By XML";
            this.tabRead.UseVisualStyleBackColor = true;
            this.btnRunRead.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRunRead.Location = new System.Drawing.Point(646, 196);
            this.btnRunRead.Name = "btnRunRead";
            this.btnRunRead.Size = new System.Drawing.Size(112, 34);
            this.btnRunRead.Text = "Run";
            this.btnRunRead.UseVisualStyleBackColor = true;
            this.btnRunRead.Click += new System.EventHandler(this.btnRunRead_Click);
            this.btnAddXmlRead.Location = new System.Drawing.Point(20, 196);
            this.btnAddXmlRead.Name = "btnAddXmlRead";
            this.btnAddXmlRead.Size = new System.Drawing.Size(150, 34);
            this.btnAddXmlRead.Text = "Add XML";
            this.btnAddXmlRead.UseVisualStyleBackColor = true;
            this.btnAddXmlRead.Click += new System.EventHandler(this.btnAddXmlRead_Click);
            this.lstXmlRead.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lstXmlRead.ItemHeight = 21;
            this.lstXmlRead.Location = new System.Drawing.Point(20, 20);
            this.lstXmlRead.Name = "lstXmlRead";
            this.lstXmlRead.Size = new System.Drawing.Size(738, 151);
            this.tabWrite.Controls.Add(this.btnRunWrite);
            this.tabWrite.Controls.Add(this.btnAddXmlWrite);
            this.tabWrite.Controls.Add(this.lstXmlWrite);
            this.tabWrite.Location = new System.Drawing.Point(4, 29);
            this.tabWrite.Name = "tabWrite";
            this.tabWrite.Padding = new System.Windows.Forms.Padding(3);
            this.tabWrite.Size = new System.Drawing.Size(776, 248);
            this.tabWrite.Text = "Write By XML";
            this.tabWrite.UseVisualStyleBackColor = true;
            this.btnRunWrite.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRunWrite.Location = new System.Drawing.Point(646, 196);
            this.btnRunWrite.Name = "btnRunWrite";
            this.btnRunWrite.Size = new System.Drawing.Size(112, 34);
            this.btnRunWrite.Text = "Run";
            this.btnRunWrite.UseVisualStyleBackColor = true;
            this.btnRunWrite.Click += new System.EventHandler(this.btnRunWrite_Click);
            this.btnAddXmlWrite.Location = new System.Drawing.Point(20, 196);
            this.btnAddXmlWrite.Name = "btnAddXmlWrite";
            this.btnAddXmlWrite.Size = new System.Drawing.Size(150, 34);
            this.btnAddXmlWrite.Text = "Add XML";
            this.btnAddXmlWrite.UseVisualStyleBackColor = true;
            this.btnAddXmlWrite.Click += new System.EventHandler(this.btnAddXmlWrite_Click);
            this.lstXmlWrite.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lstXmlWrite.ItemHeight = 21;
            this.lstXmlWrite.Location = new System.Drawing.Point(20, 20);
            this.lstXmlWrite.Name = "lstXmlWrite";
            this.lstXmlWrite.Size = new System.Drawing.Size(738, 151);
            this.tabCleanup.Controls.Add(this.btnCleanup);
            this.tabCleanup.Location = new System.Drawing.Point(4, 29);
            this.tabCleanup.Name = "tabCleanup";
            this.tabCleanup.Padding = new System.Windows.Forms.Padding(3);
            this.tabCleanup.Size = new System.Drawing.Size(776, 248);
            this.tabCleanup.Text = "Cleanup";
            this.tabCleanup.UseVisualStyleBackColor = true;
            this.btnCleanup.Location = new System.Drawing.Point(20, 20);
            this.btnCleanup.Name = "btnCleanup";
            this.btnCleanup.Size = new System.Drawing.Size(150, 34);
            this.btnCleanup.Text = "Cleanup";
            this.btnCleanup.UseVisualStyleBackColor = true;
            this.btnCleanup.Click += new System.EventHandler(this.btnCleanup_Click);
            this.tabPartitions.Controls.Add(this.splitPartitions);
            this.tabPartitions.Location = new System.Drawing.Point(4, 29);
            this.tabPartitions.Name = "tabPartitions";
            this.tabPartitions.Padding = new System.Windows.Forms.Padding(3);
            this.tabPartitions.Size = new System.Drawing.Size(776, 248);
            this.tabPartitions.Text = "Partitions";
            this.tabPartitions.UseVisualStyleBackColor = true;
            ((System.ComponentModel.ISupportInitialize)(this.splitPartitions)).BeginInit();
            this.splitPartitions.Panel1.SuspendLayout();
            this.splitPartitions.Panel2.SuspendLayout();
            this.splitPartitions.SuspendLayout();
            this.splitPartitions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitPartitions.Location = new System.Drawing.Point(3, 3);
            this.splitPartitions.Name = "splitPartitions";
            this.splitPartitions.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitPartitions.Size = new System.Drawing.Size(770, 242);
            this.splitPartitions.SplitterDistance = 180;
            this.splitPartitions.Panel1MinSize = 80;
            this.splitPartitions.Panel2MinSize = 48;
            this.splitPartitions.TabIndex = 0;
            this.splitPartitions.Panel1.Controls.Add(this.lvPartitions);
            this.splitPartitions.Panel2.Controls.Add(this.btnReadPartitions);
            this.splitPartitions.Panel2.Controls.Add(this.btnBackupSelected);
            this.splitPartitions.Panel2.Controls.Add(this.btnWriteSelected);
            this.btnReadPartitions.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnReadPartitions.Location = new System.Drawing.Point(530, 8);
            this.btnReadPartitions.Name = "btnReadPartitions";
            this.btnReadPartitions.Size = new System.Drawing.Size(112, 34);
            this.btnReadPartitions.Text = "Read";
            this.btnReadPartitions.UseVisualStyleBackColor = true;
            this.btnReadPartitions.Click += new System.EventHandler(this.btnReadPartitions_Click);
            this.lvPartitions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lvPartitions.Location = new System.Drawing.Point(0, 0);
            this.lvPartitions.Name = "lvPartitions";
            this.lvPartitions.Size = new System.Drawing.Size(770, 180);
            this.lvPartitions.View = System.Windows.Forms.View.Details;
            this.lvPartitions.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] { this.colName, this.colLun, this.colStart, this.colEnd, this.colSize, this.colType });
            this.colName.Text = "Name";
            this.colName.Width = 140;
            this.colLun.Text = "LUN";
            this.colLun.Width = 60;
            this.colStart.Text = "Start LBA";
            this.colStart.Width = 120;
            this.colEnd.Text = "End LBA";
            this.colEnd.Width = 120;
            this.colSize.Text = "Size";
            this.colSize.Width = 100;
            this.colType.Text = "Type GUID";
            this.colType.Width = 220;
            this.btnBackupSelected.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBackupSelected.Location = new System.Drawing.Point(412, 8);
            this.btnBackupSelected.Name = "btnBackupSelected";
            this.btnBackupSelected.Size = new System.Drawing.Size(112, 34);
            this.btnBackupSelected.Text = "Backup";
            this.btnBackupSelected.UseVisualStyleBackColor = true;
            this.btnBackupSelected.Click += new System.EventHandler(this.btnBackupSelected_Click);
            this.btnWriteSelected.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnWriteSelected.Location = new System.Drawing.Point(648, 8);
            this.btnWriteSelected.Name = "btnWriteSelected";
            this.btnWriteSelected.Size = new System.Drawing.Size(112, 34);
            this.btnWriteSelected.Text = "Write";
            this.btnWriteSelected.UseVisualStyleBackColor = true;
            this.btnWriteSelected.Click += new System.EventHandler(this.btnWriteSelected_Click);
            this.txtLog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtLog.Location = new System.Drawing.Point(0, 281);
            this.txtLog.Multiline = true;
            this.txtLog.Name = "txtLog";
            this.txtLog.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtLog.Size = new System.Drawing.Size(784, 180);
            this.splitMain = new System.Windows.Forms.SplitContainer();
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).BeginInit();
            this.splitMain.Panel1.SuspendLayout();
            this.splitMain.Panel2.SuspendLayout();
            this.splitMain.SuspendLayout();
            this.splitMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitMain.Location = new System.Drawing.Point(0, 0);
            this.splitMain.Name = "splitMain";
            this.splitMain.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitMain.Size = new System.Drawing.Size(784, 461);
            this.splitMain.SplitterDistance = 281;
            this.splitMain.Panel1MinSize = 240;
            this.splitMain.Panel2MinSize = 80;
            this.splitMain.Panel1.Controls.Add(this.tabControl);
            this.splitMain.Panel2.Controls.Add(this.txtLog);
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 461);
            this.Controls.Add(this.splitMain);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "OPLUS EDL Tool";
            this.tabControl.ResumeLayout(false);
            this.tabFirehose.ResumeLayout(false);
            this.tabFirehose.PerformLayout();
            this.tabRead.ResumeLayout(false);
            this.tabWrite.ResumeLayout(false);
            this.tabCleanup.ResumeLayout(false);
            this.tabPartitions.ResumeLayout(false);
            this.splitPartitions.Panel1.ResumeLayout(false);
            this.splitPartitions.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitPartitions)).EndInit();
            this.splitPartitions.ResumeLayout(false);
            this.splitMain.Panel1.ResumeLayout(false);
            this.splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).EndInit();
            this.splitMain.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabFirehose;
        private System.Windows.Forms.TabPage tabRead;
        private System.Windows.Forms.TabPage tabWrite;
        private System.Windows.Forms.TabPage tabCleanup;
        private System.Windows.Forms.TabPage tabPartitions;
        private System.Windows.Forms.Button btnRunFirehose;
        private System.Windows.Forms.Button btnBrowseSig;
        private System.Windows.Forms.Button btnBrowseDigest;
        private System.Windows.Forms.Button btnBrowseDevPrg;
        private System.Windows.Forms.TextBox txtSig;
        private System.Windows.Forms.TextBox txtDigest;
        private System.Windows.Forms.TextBox txtDevPrg;
        private System.Windows.Forms.Label lblSig;
        private System.Windows.Forms.Label lblDigest;
        private System.Windows.Forms.Label lblDevPrg;
        private System.Windows.Forms.Button btnRunRead;
        private System.Windows.Forms.Button btnAddXmlRead;
        private System.Windows.Forms.ListBox lstXmlRead;
        private System.Windows.Forms.Button btnRunWrite;
        private System.Windows.Forms.Button btnAddXmlWrite;
        private System.Windows.Forms.ListBox lstXmlWrite;
        private System.Windows.Forms.Button btnCleanup;
        private System.Windows.Forms.TextBox txtLog;
        private System.Windows.Forms.Button btnReadPartitions;
        private System.Windows.Forms.ListView lvPartitions;
        private System.Windows.Forms.ColumnHeader colName;
        private System.Windows.Forms.ColumnHeader colStart;
        private System.Windows.Forms.ColumnHeader colEnd;
        private System.Windows.Forms.ColumnHeader colSize;
        private System.Windows.Forms.ColumnHeader colType;
        private System.Windows.Forms.Button btnBackupSelected;
        private System.Windows.Forms.Button btnWriteSelected;
        private System.Windows.Forms.SplitContainer splitPartitions;
        private System.Windows.Forms.ColumnHeader colLun;
        private System.Windows.Forms.SplitContainer splitMain;
    }
}
